Update typing_inspect to 0.7.1
AnacondaRecipes/typing_inspect-feedstock pull request #2
Opened 2021-10-21 13:54 UTC by varlackc

1. check the upstream
https://github.com/ilevkivskyi/typing_inspect/tree/0.7.1

2. check the pinnings
https://github.com/ilevkivskyi/typing_inspect/blob/0.7.1/typing_inspect.py
https://github.com/ilevkivskyi/typing_inspect/blob/0.7.1/test_typing_inspect.py
https://github.com/ilevkivskyi/typing_inspect/blob/0.7.1/test-requirements.txt
https://github.com/ilevkivskyi/typing_inspect/blob/0.7.1/setup.py
https://github.com/ilevkivskyi/typing_inspect/blob/0.7.1/requirements.txt

3. check changelogs

There was no change log provided so instead, the source code for different versions were verified

https://github.com/ilevkivskyi/typing_inspect/tags

The Read Me files were inspected
https://github.com/ilevkivskyi/typing_inspect/blob/0.7.1/README.md

In addition the documentation on different versions was inspected as well
https://libraries.io/pypi/typing-inspect/0.7.1
https://libraries.io/pypi/typing-inspect/0.7.0
https://libraries.io/pypi/typing-inspect/0.6.0

After all of the research, there was no evidence of any mayor breaking change

4. additional research
There were no open issues in conda-forge
https://github.com/conda-forge/typing_inspect-feedstock/issues

5. verify dev_url
    dev_url: http://github.com/ilevkivskyi/typing_inspect
6. verify doc_url
    doc_url: https://libraries.io/pypi/typing-inspect 
7. added pip to the test section
8. verify the test section
9. additional tests

In order to test the `typing_inspect` package version `0.7.1` the following command was used:
`conda build typing_inspect-feedstock --test` 
The test result was the following:
`All tests passed`

In addition the `libcst` package was used to test the `typing_inspect` package.
The pinning for `typing_inspect` in the `libcst` package was modified to use `0.7.1`
The following command was used:
`conda build libcst-feedstock --test`
The test result was the following:
`All tests passed`

Based on the research findings and on the test results we can conclude that it is safe to update `typing_inspect` to version `0.7.1`

2021-10-21 14:24 UTC, skupr-anaconda commented
Recommend to check:
- Missing wheel package in requirements
- Missing setuptools package in requirements
- No license family specified
- No documentation url provided
- No development url provided

2021-10-21 20:16 UTC, varlackc commented
> Recommend to check:
> 
> * Missing wheel package in requirements
> * Missing setuptools package in requirements
> * No license family specified
> * No documentation url provided
> * No development url provided

`Setuptools` and `wheels` are included in the meta.yaml file
https://github.com/AnacondaRecipes/typing_inspect-feedstock/blob/update_to_0.7.1/recipe/meta.yaml#L22&L23

The `license_family`, `dev_url` and `doc_url` are included in the meta.yaml file
https://github.com/AnacondaRecipes/typing_inspect-feedstock/blob/update_to_0.7.1/recipe/meta.yaml#L42&L45

2021-10-22 07:15 UTC, skupr-anaconda approved these changes

2021-10-22 09:08 UTC, katietz requested changes

2021-10-22 09:08 UTC, katietz commented on recipe/meta.yaml
> +  skip: true  # [s390x]
pleas add here also a skip for python less 3.6

2021-10-22 09:08 UTC, katietz commented on recipe/meta.yaml
> +  skip: true  # [s390x]
What is the cause for disabling here s390x? Missing dependencies?
If so, add a comment for it, additional it would be good to add jira ticket for the missing dependency on s390x

2021-10-26 17:01 UTC, varlackc commented on recipe/meta.yaml
> +  skip: true  # [s390x]
A comment was added to the skip section to explain why the skip was added. 
There seem to be issues with missing dependencies in s390x

https://github.com/AnacondaRecipes/typing_inspect-feedstock/blob/update_to_0.7.1/recipe/meta.yaml#L14&L15

2021-10-27 05:30 UTC, katietz requested changes
Please specify in comment more detailed

2021-10-27 05:30 UTC, katietz commented on recipe/meta.yaml
> +  # s390x has missing dependencies
What missing dependencies?

2021-10-28 04:33 UTC, varlackc commented on recipe/meta.yaml
> +  # s390x has missing dependencies
`mypy_extensions >=0.3.0` seem to be missing in `s390x`

https://github.com/AnacondaRecipes/typing_inspect-feedstock/blob/update_to_0.7.1/recipe/meta.yaml#L14&L15

2021-10-28 04:38 UTC, varlackc commented on recipe/meta.yaml
>    noarch: python
Specified the missing dependency in s390x and the version pinning

2021-10-28 12:12 UTC, katietz requested changes

2021-10-28 12:12 UTC, katietz commented on recipe/meta.yaml
> +  skip: true  # [py<3.6 or s390x]
once again ... don't use here 3.6 ... IT IS 36 !

2021-10-29 07:09 UTC, katietz approved these changes
Thanks

2021-10-29 22:31 UTC, merged